import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Freelance Pricing Guide: Rates, Projects & Retainers", description: "A practical freelance pricing guide covering rate floors, billable capacity, fixed fees, retainers, discounts, negotiation, and annual rate reviews.", alternates: { canonical: "/guides/freelance-pricing" } };

export default function PricingGuidePage() {
  return <main id="main"><section className="page-hero"><div className="shell"><p className="eyebrow">FIELD GUIDE / PRICING</p><h1>Price the business you want to keep running.</h1><p>A practical system for setting a rate floor, choosing the right pricing model, handling scope, and reviewing your numbers before undercharging becomes a habit.</p></div></section><article className="content-shell">
    <p><strong>Good freelance pricing does three jobs at once:</strong> it funds your personal income, covers the cost and uncertainty of operating independently, and makes sense relative to the value and alternatives available to the client. No single formula can decide all three, but a transparent cost floor gives every later decision a safer starting point.</p>
    <h2>1. Start with a rate floor</h2><p>Your floor is the minimum average rate that makes the annual plan work. It should include the amount you want to keep, the benefits you now fund yourself, estimated taxes, operating costs, and the number of hours you can realistically invoice.</p>
    <div className="note-box"><strong>Rate floor = required annual revenue ÷ realistic annual billable hours</strong><p>Required revenue is not the same as take-home income. Billable hours are not the same as total working hours.</p></div>
    <h3>Use an effective tax estimate</h3><p>An effective rate is the average share of taxable profit you expect to pay, not necessarily your highest marginal bracket. Business structure, location, deductions, and social contributions can change the result materially. Use your own records or professional guidance when possible.</p>
    <h3>Count benefits as part of owner compensation</h3><p>Health coverage, retirement contributions, disability insurance, paid leave replacement, and professional development are easy to omit because they do not arrive as a monthly salary. Omitting them does not make them free; it moves the cost into your future.</p>
    <h2>2. Model billable capacity honestly</h2><p>A forty-hour workweek rarely creates forty invoiceable hours. Sales, proposals, follow-ups, bookkeeping, scheduling, marketing, research, training, and gaps between engagements consume capacity. Start with tracked data if you have it. If you do not, test a conservative range rather than choosing the most optimistic case.</p>
    <p>For example, 40 total hours × 62% billable time × 47 working weeks produces about 1,166 billable hours—not 2,080. That denominator can matter more than a small change in expenses.</p>
    <h2>3. Keep three rate signals</h2><ul><li><strong>Floor:</strong> the plan works, but there is little room for reinvestment or slow periods.</li><li><strong>Target:</strong> the normal quote for clear, well-managed client work.</li><li><strong>High-risk:</strong> a reference point for urgency, weak scope, unusual responsibility, or opportunity cost.</li></ul>
    <p>These are internal decision signals, not necessarily a public menu. A client usually needs a clear price and scope, not your entire financial model.</p>
    <h2>4. Match the pricing model to the work</h2>
    <h3>Hourly</h3><p>Hourly pricing fits open-ended support, discovery, or work where the client controls priorities. It limits estimation risk but can punish efficiency and makes budgets less certain.</p>
    <h3>Day rate</h3><p>Day rates are useful for workshops, on-site delivery, production blocks, or consulting sessions. Define the booking window, overtime, preparation, follow-up, travel, and cancellation terms. Use the <Link href="/day-rate-calculator">day rate calculator</Link> to model booking options.</p>
    <h3>Fixed project fee</h3><p>Fixed fees fit work with defined outcomes and boundaries. Include delivery, communication, project management, external costs, revision exposure, and a reserve for normal uncertainty. The <Link href="/project-pricing-calculator">project calculator</Link> keeps those parts visible.</p>
    <h3>Retainer</h3><p>A retainer buys access to a defined amount or type of capacity. Spell out rollover, response times, overages, priorities, exclusions, and the renewal or cancellation window. A modest commitment adjustment can make sense when predictable demand lowers sales and scheduling costs; avoid discounting simply because the invoice repeats.</p>
    <h2>5. Negotiate scope before rate</h2><p>When the budget is lower than the quote, change a lever: fewer deliverables, fewer revisions, slower delivery, less access, narrower usage rights, a phased rollout, or client-owned project management. A silent rate cut keeps the workload while removing the margin that made it viable.</p>
    <h2>6. Review the plan every quarter</h2><p>Check realized billable percentage, average collected rate, write-offs, unpaid time, pipeline gaps, expense changes, and which services create the strongest client outcomes. Raise or reshape pricing when the data changes—not only when you feel overworked.</p>
    <div className="note-box"><strong>A useful rate review question:</strong><p>If every client accepted this exact price and workload next year, would the business become healthier or more fragile?</p></div>
    <h2>Build your numbers</h2><p>Use the <Link href="/#calculator">advanced freelance rate calculator</Link> to produce a floor, target, day rate, retainer, and project checkpoint from one consistent annual plan.</p>
  </article></main>;
}
