import type { Metadata } from "next";
import Link from "next/link";
import FocusedCalculator from "../components/FocusedCalculator";

export const metadata: Metadata = { title: "Salary to Freelance Rate Calculator", description: "Convert an employee salary into a freelance hourly rate by including benefits, business expenses, estimated taxes, and realistic billable hours.", alternates: { canonical: "/salary-to-freelance-rate" } };

export default function SalaryConverterPage() {
  return <main id="main"><section className="page-hero"><div className="shell"><p className="eyebrow">SALARY → FREELANCE</p><h1>Replace the package, not just the paycheck.</h1><p>Translate salary, benefits, paid time off, business overhead, taxes, and billable capacity into the client revenue your independent practice needs.</p></div></section><FocusedCalculator mode="salary" /><article className="content-shell"><h2>Why salary and freelance revenue are not equivalent</h2><p>An employee salary is only one part of employment compensation. Employers may also fund payroll taxes, health coverage, retirement contributions, equipment, paid leave, professional development, and the time between internal assignments. A freelancer purchases or absorbs those benefits directly.</p><h2>A more useful conversion method</h2><ol><li>Add the estimated annual value of benefits and paid leave to the salary you want to replace.</li><li>Gross that owner-compensation goal up for your estimated effective tax rate.</li><li>Add the annual costs of running the business.</li><li>Divide by realistic billable hours—not 2,080 calendar working hours.</li></ol><div className="note-box"><strong>This is a planning model, not a tax calculator.</strong><p>Business structure, deductions, payroll obligations, social insurance, and benefits differ by country and individual situation.</p></div><h3>Use market information as a second check</h3><p>Cost-based pricing tells you whether freelancing supports your plan. It does not guarantee the market will accept the number. Compare it with the value of your outcomes, alternatives available to the client, positioning, experience, and demand.</p><p>For project and retainer equivalents, continue with the <Link href="/#calculator">complete rate planner</Link>.</p></article></main>;
}
