import type { Metadata } from "next";
import Link from "next/link";
import FocusedCalculator from "../components/FocusedCalculator";

export const metadata: Metadata = { title: "Freelance Day Rate Calculator", description: "Calculate a freelance or consulting day rate, half-day minimum, weekly booking rate, and monthly capacity from your sustainable hourly rate.", alternates: { canonical: "/day-rate-calculator" } };

export default function DayRatePage() {
  return <main id="main"><section className="page-hero"><div className="shell"><p className="eyebrow">DAY RATE CALCULATOR</p><h1>Price the day you are actually reserving.</h1><p>Convert an hourly target into full-day, half-day, multi-day, and monthly booking rates without quietly giving away your capacity.</p></div></section><FocusedCalculator mode="day" /><article className="content-shell"><h2>A day rate is a capacity commitment</h2><p>A client booking a day is buying more than the visible meeting or production time. That booking can prevent you from accepting other work, split your week, and create preparation and follow-up that never appears on a timesheet.</p><h2>Day rate formula</h2><div className="note-box"><strong>Day rate = sustainable hourly rate × billable hours reserved</strong><p>Apply a multi-day adjustment only when the commitment creates real savings: less sales work, lower context switching, or predictable utilization.</p></div><h3>Do not turn an eight-hour day into unlimited access</h3><p>Define the working window, breaks, deliverables, communication channel, overtime treatment, and what happens when the client delays decisions. A day rate is a booking model, not a waiver of scope.</p><h3>Half-days often need a premium</h3><p>A four-hour session can consume most of a usable day after travel, preparation, and transition time. That is why the calculator uses 65% of the full-day rate as its default half-day reference, not 50%.</p><p>Need to build the underlying hourly target first? Use the <Link href="/#calculator">full freelance rate calculator</Link>.</p></article></main>;
}
