import type { Metadata } from "next";
import Link from "next/link";
import FocusedCalculator from "../components/FocusedCalculator";

export const metadata: Metadata = { title: "Freelance Project Pricing Calculator", description: "Calculate a fixed project fee from delivery time, project management, external costs, revisions, uncertainty, risk, and client value.", alternates: { canonical: "/project-pricing-calculator" } };

export default function ProjectPricingPage() {
  return <main id="main"><section className="page-hero"><div className="shell"><p className="eyebrow">PROJECT PRICE CALCULATOR</p><h1>Quote the scope, uncertainty, and outcome.</h1><p>Build a fixed fee from the real delivery effort, external costs, revision exposure, coordination risk, and value at stake.</p></div></section><FocusedCalculator mode="project" /><article className="content-shell"><h2>A fixed fee moves risk to the freelancer</h2><p>Hourly work charges for time as it occurs. A fixed fee gives the client price certainty, which means you carry more risk when estimates, feedback cycles, dependencies, or decision-making expand. The quote should pay for that transfer of risk.</p><h2>What belongs in project hours</h2><ul><li>Discovery, research, and preparation</li><li>Production and quality assurance</li><li>Project management and client communication</li><li>Revisions included in the scope</li><li>Delivery, handoff, and closeout</li></ul><h3>Separate reserve from value</h3><p>A scope reserve protects the estimate from normal uncertainty. A value or risk adjustment reflects the commercial impact, urgency, exclusivity, intellectual-property rights, or downside you accept. Keeping them separate makes review and negotiation clearer.</p><div className="note-box"><strong>Price first, discount second.</strong><p>If a budget requires a lower fee, reduce scope, rights, speed, or service level. An unexplained discount teaches the client that the original quote was flexible.</p></div><p>Need a sustainable hourly base? Start with the <Link href="/#calculator">full RatePilot calculator</Link>.</p></article></main>;
}
